### ISSUE TITLE
Webpack Config Has Wrong Library Export Name

### ISSUE THREAD

**Issue by CitrusFruits** [cssinjs/jss-cache#1]
Line 19 of webpack.config.js should read `library: 'jssCache',`. Right now it reads ` library: 'jssCamelCase',`

I'm still familiarizing myself with this framework, but I'm pretty sure this is a bug.

**Comment by kof** [comment]
yep, thanks, wanna send me a patch?

**Comment by CitrusFruits** [comment]
Sure just made a PR.

**Comment by kof** [comment]
released in 2.0.1
